import {
  Exercise,
  WorkoutRoutine,
  CompletedWorkout,
  FoodItem,
  LoggedFoodItem,
  WaterLog,
  WeightEntry,
  UserProfile,
  AppSettings,
} from '../types';

export const SEED_USER_PROFILE: UserProfile = {
  id: 'user-apex-01',
  name: 'Alex Mercer',
  gender: 'male',
  age: 26,
  heightCm: 178,
  weightKg: 78.4,
  startWeightKg: 82.0,
  targetWeightKg: 75.0,
  activityLevel: 'very_active',
  fitnessGoal: 'build_muscle',
  trainingDaysGoal: 5,
  bmr: 1750,
  tdee: 2650,
  targetCalories: 2400,
  targetProteinG: 165,
  targetCarbsG: 260,
  targetFatG: 65,
  targetFiberG: 32,
  targetWaterMl: 3200,
  isManualMacroOverride: false,
  isOnboarded: true,
  createdAt: '2026-07-01T08:00:00Z',
};

export const SEED_APP_SETTINGS: AppSettings = {
  theme: 'dark',
  weightUnit: 'kg',
  waterUnit: 'ml',
  soundEnabled: true,
  hapticsEnabled: true,
  restTimerAutoStart: true,
  defaultRestSeconds: 90,
};

export const SEED_EXERCISES: Exercise[] = [
  // CHEST
  {
    id: 'ex-barbell-bench-press',
    name: 'Barbell Bench Press',
    targetMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: 'Barbell',
    movementPattern: 'Push',
    difficulty: 'Intermediate',
    instructions: [
      'Lie flat on the bench with eyes directly beneath the racked barbell.',
      'Grip the bar slightly wider than shoulder-width with wrists straight.',
      'Unrack, take a deep breath, and lower the bar under control to mid-chest.',
      'Drive feet into the floor and press the bar explosively back to lockout.',
    ],
    tips: [
      'Keep shoulder blades retracted and depressed throughout the movement.',
      'Tuck elbows at a 45-degree angle rather than flaring them out wide.',
    ],
    personalRecord: {
      weightKg: 100,
      reps: 5,
      calculated1RM: 116,
      date: '2026-08-20',
    },
  },
  {
    id: 'ex-incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    targetMuscle: 'Chest',
    secondaryMuscles: ['Shoulders', 'Triceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Push',
    difficulty: 'Intermediate',
    instructions: [
      'Set bench to a 30-degree incline.',
      'Kick dumbbells up to shoulder level and sit back.',
      'Press dumbbells upward until arms are extended, bringing them slightly together at the top.',
      'Lower weights under control until you feel a deep stretch in the upper chest.',
    ],
    tips: [
      'Avoid setting incline higher than 45 degrees to prevent excessive front delt takeover.',
      'Control the 3-second eccentric phase for maximum hypertrophy.',
    ],
    personalRecord: {
      weightKg: 34,
      reps: 8,
      calculated1RM: 43,
      date: '2026-08-24',
    },
  },
  {
    id: 'ex-cable-chest-fly',
    name: 'Standing Cable Chest Fly',
    targetMuscle: 'Chest',
    secondaryMuscles: ['Shoulders'],
    equipment: 'Cable',
    movementPattern: 'Push',
    difficulty: 'Beginner',
    instructions: [
      'Set pulleys at chest height, grab handles, and take a staggered step forward.',
      'Keep a slight bend in your elbows and squeeze chest to bring hands together in front.',
      'Hold the peak contraction for 1 second, then slowly return to the stretch.',
    ],
    tips: [
      'Imagine hugging a large barrel to maintain constant chest tension.',
    ],
    personalRecord: {
      weightKg: 18,
      reps: 12,
      calculated1RM: 25,
      date: '2026-08-18',
    },
  },
  {
    id: 'ex-dips-chest',
    name: 'Chest Dips',
    targetMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: 'Bodyweight',
    movementPattern: 'Push',
    difficulty: 'Intermediate',
    instructions: [
      'Grip parallel dip bars and support your bodyweight.',
      'Lean torso forward roughly 30 degrees to target lower chest.',
      'Lower yourself until upper arms are parallel to the ground.',
      'Press through palms to return to starting position without locking elbows harshly.',
    ],
    tips: [
      'Add weight via a dip belt once you can perform 15 clean bodyweight reps.',
    ],
    personalRecord: {
      weightKg: 20,
      reps: 8,
      calculated1RM: 25,
      date: '2026-08-15',
    },
  },

  // BACK
  {
    id: 'ex-conventional-deadlift',
    name: 'Barbell Conventional Deadlift',
    targetMuscle: 'Back',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    movementPattern: 'Hinge',
    difficulty: 'Advanced',
    instructions: [
      'Stand with mid-foot under the barbell, feet hip-width apart.',
      'Hinge hips back and grip bar outside legs.',
      'Pull slack out of the bar, engage lats, keep chest proud.',
      'Drive through the floor with your legs and extend hips to stand tall.',
    ],
    tips: [
      'Never round your lower spine; brace core like you are about to take a punch.',
    ],
    personalRecord: {
      weightKg: 150,
      reps: 4,
      calculated1RM: 170,
      date: '2026-08-22',
    },
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Wide-Grip Lat Pulldown',
    targetMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Shoulders'],
    equipment: 'Cable',
    movementPattern: 'Pull',
    difficulty: 'Beginner',
    instructions: [
      'Sit facing the machine with thighs firmly secured under the pads.',
      'Grip the bar slightly wider than shoulder-width with overhand grip.',
      'Pull bar down smoothly towards upper clavicle while depressing scapulae.',
      'Slowly resist weight back up to full overhead stretch.',
    ],
    tips: [
      'Drive down with your elbows rather than pulling with your forearm flexors.',
    ],
    personalRecord: {
      weightKg: 75,
      reps: 10,
      calculated1RM: 100,
      date: '2026-08-26',
    },
  },
  {
    id: 'ex-barbell-bent-row',
    name: 'Barbell Bent-Over Row',
    targetMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Core'],
    equipment: 'Barbell',
    movementPattern: 'Pull',
    difficulty: 'Intermediate',
    instructions: [
      'Hinge forward at 45 degrees with knees slightly bent and spine neutral.',
      'Grip bar with overhand grip just outside knees.',
      'Row barbell towards lower ribcage/belly button by driving elbows back.',
      'Squeeze shoulder blades together, then lower under control.',
    ],
    tips: ['Keep torso locked; avoid bouncing with your hips to generate momentum.'],
    personalRecord: {
      weightKg: 85,
      reps: 6,
      calculated1RM: 102,
      date: '2026-08-26',
    },
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row (Close Grip)',
    targetMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Shoulders'],
    equipment: 'Cable',
    movementPattern: 'Pull',
    difficulty: 'Beginner',
    instructions: [
      'Sit on bench with feet placed on footrests, knees slightly bent.',
      'Grip V-bar handle with neutral spine.',
      'Pull handle into lower abdomen while keeping elbows tucked.',
      'Control the return, letting lats stretch forward without rounding lower back.',
    ],
    tips: ['Focus on pulling your elbows past your ribcage.'],
    personalRecord: {
      weightKg: 70,
      reps: 10,
      calculated1RM: 93,
      date: '2026-08-19',
    },
  },

  // SHOULDERS
  {
    id: 'ex-overhead-press',
    name: 'Overhead Barbell Military Press',
    targetMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Core'],
    equipment: 'Barbell',
    movementPattern: 'Push',
    difficulty: 'Intermediate',
    instructions: [
      'Stand with feet shoulder-width, bar resting across front delts and collarbone.',
      'Squeeze glutes and brace core.',
      'Press barbell straight up, moving head slightly back until bar clears, then lock out overhead.',
      'Lower smoothly back to clavicle.',
    ],
    tips: ['Keep glutes clenched hard to prevent hyperextending your lumbar spine.'],
    personalRecord: {
      weightKg: 65,
      reps: 5,
      calculated1RM: 75,
      date: '2026-08-20',
    },
  },
  {
    id: 'ex-dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    targetMuscle: 'Shoulders',
    secondaryMuscles: ['Traps'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    instructions: [
      'Hold dumbbells at sides with a slight forward torso tilt.',
      'Raise arms out laterally until parallel with the floor with elbows slightly bent.',
      'Pause briefly at parallel, then lower with a controlled 2-second tempo.',
    ],
    tips: ['Lead with the elbows and avoid shrugging traps.'],
    personalRecord: {
      weightKg: 14,
      reps: 12,
      calculated1RM: 19,
      date: '2026-08-27',
    },
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Face Pull with Rope',
    targetMuscle: 'Shoulders',
    secondaryMuscles: ['Back'],
    equipment: 'Cable',
    movementPattern: 'Pull',
    difficulty: 'Beginner',
    instructions: [
      'Set cable pulley at eye height with a dual-rope attachment.',
      'Grip ropes with thumbs facing back.',
      'Pull rope towards eyes while rotating hands out and back.',
      'Squeeze rear deltoids and external rotators at the back of the motion.',
    ],
    tips: ['High reps (15-20) work best for shoulder joint longevity.'],
    personalRecord: {
      weightKg: 25,
      reps: 15,
      calculated1RM: 37,
      date: '2026-08-27',
    },
  },

  // LEGS
  {
    id: 'ex-barbell-back-squat',
    name: 'Barbell Back Squat',
    targetMuscle: 'Legs',
    secondaryMuscles: ['Quads', 'Glutes', 'Core'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    instructions: [
      'Rest barbell securely across upper traps with hands gripping firmly.',
      'Step back, feet shoulder-width, toes angled slightly out.',
      'Inhale deep, brace core, and sit hips down between knees until hip crease is below knee level.',
      'Drive powerfully through mid-foot to stand back up.',
    ],
    tips: ['Keep knees tracking in line with your toes throughout the descent and ascent.'],
    personalRecord: {
      weightKg: 130,
      reps: 5,
      calculated1RM: 151,
      date: '2026-08-21',
    },
  },
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift (Dumbbell/Barbell)',
    targetMuscle: 'Legs',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Back'],
    equipment: 'Dumbbell',
    movementPattern: 'Hinge',
    difficulty: 'Intermediate',
    instructions: [
      'Stand holding weights in front of thighs with slight soft knee bend.',
      'Push hips directly backward while keeping weights grazing down your legs.',
      'Stop when you feel deep tension in your hamstrings without rounding lower back.',
      'Drive hips forward to return to standing.',
    ],
    tips: ['Think about touching a wall behind you with your glutes.'],
    personalRecord: {
      weightKg: 40,
      reps: 10,
      calculated1RM: 53,
      date: '2026-08-21',
    },
  },
  {
    id: 'ex-leg-press',
    name: '45-Degree Incline Leg Press',
    targetMuscle: 'Legs',
    secondaryMuscles: ['Quads', 'Glutes'],
    equipment: 'Machine',
    movementPattern: 'Squat',
    difficulty: 'Beginner',
    instructions: [
      'Sit in machine with lower back firmly pressed into pad.',
      'Place feet shoulder-width in center of sled.',
      'Release safety pins and lower sled until knees reach 90 degrees.',
      'Press through heels and mid-foot to return, avoiding knee hyperextension.',
    ],
    tips: ['Never let your lower back or pelvis lift off the backrest at the bottom.'],
    personalRecord: {
      weightKg: 240,
      reps: 10,
      calculated1RM: 320,
      date: '2026-08-25',
    },
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg Extension Machine',
    targetMuscle: 'Quads',
    secondaryMuscles: [],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    instructions: [
      'Adjust pad so it rests on lower shins just above ankles.',
      'Align knee joints directly with the machine pivot point.',
      'Extend legs upward until quads are fully locked and contracted.',
      'Slowly lower weight back over 3 seconds.',
    ],
    tips: ['Point toes slightly upward and hold the top contraction for 1 second.'],
    personalRecord: {
      weightKg: 65,
      reps: 12,
      calculated1RM: 91,
      date: '2026-08-25',
    },
  },
  {
    id: 'ex-seated-leg-curl',
    name: 'Seated Hamstring Leg Curl',
    targetMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    instructions: [
      'Sit with thigh pad securely fastened down and pad resting behind lower calves.',
      'Curl legs down and back as far as possible.',
      'Squeeze hamstrings, then control return to the top.',
    ],
    tips: ['Keep toes dorsiflexed (pulled up toward knees) for optimal hamstring recruitment.'],
    personalRecord: {
      weightKg: 55,
      reps: 12,
      calculated1RM: 77,
      date: '2026-08-25',
    },
  },
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    targetMuscle: 'Calves',
    secondaryMuscles: [],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    instructions: [
      'Place balls of feet on edge of platform with shoulder pads adjusted.',
      'Lower heels below platform level for a full deep stretch.',
      'Drive onto the balls of your big toes for peak calf contraction.',
      'Pause for 2 seconds at the peak before lowering.',
    ],
    tips: ['Calves respond best to full range of motion and eliminating rebound bounce.'],
    personalRecord: {
      weightKg: 80,
      reps: 15,
      calculated1RM: 120,
      date: '2026-08-25',
    },
  },

  // ARMS
  {
    id: 'ex-barbell-bicep-curl',
    name: 'EZ-Bar Bicep Curl',
    targetMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Barbell',
    movementPattern: 'Pull',
    difficulty: 'Beginner',
    instructions: [
      'Grip the inner curves of the EZ-bar with palms facing forward.',
      'Keep elbows pinned to your ribs and curl bar up towards collarbone.',
      'Squeeze biceps hard at top, then lower smoothly over 3 seconds.',
    ],
    tips: ['Keep upper arms vertical without swinging shoulders forward.'],
    personalRecord: {
      weightKg: 38,
      reps: 8,
      calculated1RM: 48,
      date: '2026-08-26',
    },
  },
  {
    id: 'ex-incline-dumbbell-curl',
    name: 'Incline Dumbbell Bicep Curl',
    targetMuscle: 'Biceps',
    secondaryMuscles: [],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    instructions: [
      'Lie back on 45-degree incline bench with dumbbells hanging straight down.',
      'Curl weights upward while supinating wrists (turning palms up).',
      'Lower under complete control into the deep long-head stretch.',
    ],
    tips: ['The stretch at the bottom produces intense hypertrophic stimuli.'],
    personalRecord: {
      weightKg: 16,
      reps: 10,
      calculated1RM: 21,
      date: '2026-08-26',
    },
  },
  {
    id: 'ex-cable-tricep-pushdown',
    name: 'Cable Tricep Rope Pushdown',
    targetMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Cable',
    movementPattern: 'Push',
    difficulty: 'Beginner',
    instructions: [
      'Attach rope to high pulley, stand close, elbows tucked at sides.',
      'Push rope downward until elbows are fully locked, spreading rope ends apart at bottom.',
      'Control return to chest level.',
    ],
    tips: ['Flare the rope ends outward at full extension for peak lateral head tension.'],
    personalRecord: {
      weightKg: 30,
      reps: 12,
      calculated1RM: 42,
      date: '2026-08-24',
    },
  },
  {
    id: 'ex-skull-crushers',
    name: 'Lying EZ-Bar Skull Crushers',
    targetMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Barbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    instructions: [
      'Lie flat holding EZ-bar with arms vertical over chest.',
      'Hinge only at the elbows to lower bar toward forehead or slightly behind crown of head.',
      'Extend elbows to return to start.',
    ],
    tips: ['Angling upper arms slightly back toward your head keeps continuous triceps tension.'],
    personalRecord: {
      weightKg: 35,
      reps: 10,
      calculated1RM: 46,
      date: '2026-08-24',
    },
  },

  // CORE & CARDIO
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg / Knee Raise',
    targetMuscle: 'Core',
    secondaryMuscles: ['Abs'],
    equipment: 'Bodyweight',
    movementPattern: 'Compound',
    difficulty: 'Intermediate',
    instructions: [
      'Hang from pull-up bar with overhand grip, shoulders engaged.',
      'Roll pelvis up and raise straight legs (or bent knees) toward chest.',
      'Pause at parallel, lower smoothly without swinging.',
    ],
    tips: ['Focus on flexing the spine and curling your pelvis upward, not just lifting thighs.'],
    personalRecord: {
      weightKg: 0,
      reps: 15,
      calculated1RM: 0,
      date: '2026-08-27',
    },
  },
  {
    id: 'ex-cable-woodchopper',
    name: 'Cable High-to-Low Woodchopper',
    targetMuscle: 'Core',
    secondaryMuscles: ['Abs', 'Shoulders'],
    equipment: 'Cable',
    movementPattern: 'Compound',
    difficulty: 'Beginner',
    instructions: [
      'Set pulley to top position, stand sideways to cable.',
      'Grip handle with both hands and rotate torso diagonally downward across opposite knee.',
      'Pivot on rear foot and engage obliques.',
    ],
    tips: ['Rotate with your torso and core rather than pulling primarily with your arms.'],
    personalRecord: {
      weightKg: 20,
      reps: 12,
      calculated1RM: 28,
      date: '2026-08-27',
    },
  },
  {
    id: 'ex-hiit-treadmill-sprints',
    name: 'HIIT Incline Treadmill Sprints',
    targetMuscle: 'Cardio',
    secondaryMuscles: ['Legs', 'Calves'],
    equipment: 'Cardio Equipment',
    movementPattern: 'Cardio',
    difficulty: 'Intermediate',
    instructions: [
      'Warm up for 3 minutes at light jog.',
      'Set incline to 4-6% and sprint at 85-95% max speed for 30 seconds.',
      'Hop off to side rails or slow belt for 60 seconds recovery.',
      'Repeat for 8-10 rounds.',
    ],
    tips: ['Maintain upright posture and high knee drive during sprints.'],
    personalRecord: {
      weightKg: 0,
      reps: 10,
      calculated1RM: 0,
      date: '2026-08-28',
    },
  },
];

export const SEED_ROUTINES: WorkoutRoutine[] = [
  {
    id: 'routine-push-power',
    name: 'Push Day - Hypertrophy & Power',
    description: 'Target chest, front/side delts, and triceps with heavy compound pressing and targeted isolation.',
    category: 'Push',
    estimatedMinutes: 55,
    difficulty: 'Intermediate',
    tags: ['Chest', 'Shoulders', 'Triceps', 'Hypertrophy'],
    timesCompleted: 14,
    lastPerformedDate: '2026-08-30',
    exercises: [
      {
        exerciseId: 'ex-barbell-bench-press',
        targetSets: 4,
        targetRepsMin: 6,
        targetRepsMax: 8,
        targetWeightKg: 85,
        restSeconds: 120,
        notes: 'Heavy working sets. Focus on leg drive and bar speed.',
      },
      {
        exerciseId: 'ex-incline-dumbbell-press',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 12,
        targetWeightKg: 30,
        restSeconds: 90,
        notes: '30 degree bench. 3 second negative tempo.',
      },
      {
        exerciseId: 'ex-overhead-press',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 10,
        targetWeightKg: 50,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-dumbbell-lateral-raise',
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 15,
        targetWeightKg: 12,
        restSeconds: 60,
        notes: 'Strict form, no swinging.',
      },
      {
        exerciseId: 'ex-cable-tricep-pushdown',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        targetWeightKg: 27,
        restSeconds: 60,
      },
    ],
  },
  {
    id: 'routine-pull-strength',
    name: 'Pull Day - Lat & Upper Back Shred',
    description: 'Complete back thickness and width routine with bicep burnout.',
    category: 'Pull',
    estimatedMinutes: 60,
    difficulty: 'Intermediate',
    tags: ['Back', 'Lats', 'Biceps', 'Strength'],
    timesCompleted: 12,
    lastPerformedDate: '2026-08-28',
    exercises: [
      {
        exerciseId: 'ex-conventional-deadlift',
        targetSets: 4,
        targetRepsMin: 4,
        targetRepsMax: 6,
        targetWeightKg: 135,
        restSeconds: 150,
      },
      {
        exerciseId: 'ex-lat-pulldown',
        targetSets: 4,
        targetRepsMin: 8,
        targetRepsMax: 12,
        targetWeightKg: 68,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-barbell-bent-row',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 10,
        targetWeightKg: 75,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-rear-delt-fly',
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 20,
        targetWeightKg: 22,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-barbell-bicep-curl',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 32,
        restSeconds: 60,
      },
    ],
  },
  {
    id: 'routine-leg-quads-glutes',
    name: 'Leg Day - Quad & Posterior Chain',
    description: 'High-intensity leg workout for quad definition, hamstring stretch, and glute activation.',
    category: 'Legs',
    estimatedMinutes: 65,
    difficulty: 'Advanced',
    tags: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
    timesCompleted: 11,
    lastPerformedDate: '2026-08-29',
    exercises: [
      {
        exerciseId: 'ex-barbell-back-squat',
        targetSets: 4,
        targetRepsMin: 6,
        targetRepsMax: 8,
        targetWeightKg: 115,
        restSeconds: 120,
      },
      {
        exerciseId: 'ex-romanian-deadlift',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 10,
        targetWeightKg: 36,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-leg-press',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 200,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-seated-leg-curl',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        targetWeightKg: 50,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-standing-calf-raise',
        targetSets: 4,
        targetRepsMin: 15,
        targetRepsMax: 20,
        targetWeightKg: 70,
        restSeconds: 45,
      },
    ],
  },
  {
    id: 'routine-upper-hypertrophy',
    name: 'Upper Body Savage',
    description: 'Balanced upper body superset routine for maximum pump and hypertrophy.',
    category: 'Upper',
    estimatedMinutes: 50,
    difficulty: 'Intermediate',
    tags: ['Chest', 'Back', 'Arms', 'Shoulders'],
    timesCompleted: 8,
    lastPerformedDate: '2026-08-26',
    exercises: [
      {
        exerciseId: 'ex-incline-dumbbell-press',
        targetSets: 4,
        targetRepsMin: 8,
        targetRepsMax: 10,
        targetWeightKg: 32,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-seated-cable-row',
        targetSets: 4,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 65,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-dumbbell-lateral-raise',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        targetWeightKg: 12,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-incline-dumbbell-curl',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 14,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-skull-crushers',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 30,
        restSeconds: 60,
      },
    ],
  },
  {
    id: 'routine-full-body-core',
    name: 'Full Body Core & Conditioning',
    description: 'High metabolic burn full body session with rotational core and sprint intervals.',
    category: 'Full Body',
    estimatedMinutes: 45,
    difficulty: 'Beginner',
    tags: ['Conditioning', 'Core', 'Cardio', 'Fat Loss'],
    timesCompleted: 6,
    lastPerformedDate: '2026-08-23',
    exercises: [
      {
        exerciseId: 'ex-barbell-back-squat',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 90,
        restSeconds: 90,
      },
      {
        exerciseId: 'ex-cable-chest-fly',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        targetWeightKg: 16,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-lat-pulldown',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        targetWeightKg: 60,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-hanging-leg-raise',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        targetWeightKg: 0,
        restSeconds: 60,
      },
      {
        exerciseId: 'ex-hiit-treadmill-sprints',
        targetSets: 8,
        targetRepsMin: 1,
        targetRepsMax: 1,
        targetWeightKg: 0,
        restSeconds: 60,
      },
    ],
  },
];

export const SEED_COMPLETED_WORKOUTS: CompletedWorkout[] = [
  {
    id: 'cw-01',
    routineId: 'routine-push-power',
    routineName: 'Push Day - Hypertrophy & Power',
    startTime: '2026-08-30T09:00:00Z',
    endTime: '2026-08-30T09:55:00Z',
    date: '2026-08-30',
    durationSeconds: 3300,
    totalVolumeKg: 8940,
    totalSetsCompleted: 17,
    totalRepsCompleted: 148,
    caloriesBurned: 410,
    exercises: [
      {
        exerciseId: 'ex-barbell-bench-press',
        exerciseName: 'Barbell Bench Press',
        targetMuscle: 'Chest',
        sets: [
          { setNumber: 1, weightKg: 80, reps: 8, isCompleted: true },
          { setNumber: 2, weightKg: 85, reps: 8, isCompleted: true },
          { setNumber: 3, weightKg: 85, reps: 7, isCompleted: true },
          { setNumber: 4, weightKg: 87.5, reps: 6, isCompleted: true },
        ],
      },
      {
        exerciseId: 'ex-incline-dumbbell-press',
        exerciseName: 'Incline Dumbbell Press',
        targetMuscle: 'Chest',
        sets: [
          { setNumber: 1, weightKg: 30, reps: 10, isCompleted: true },
          { setNumber: 2, weightKg: 32, reps: 10, isCompleted: true },
          { setNumber: 3, weightKg: 32, reps: 8, isCompleted: true },
        ],
      },
      {
        exerciseId: 'ex-overhead-press',
        exerciseName: 'Overhead Barbell Military Press',
        targetMuscle: 'Shoulders',
        sets: [
          { setNumber: 1, weightKg: 50, reps: 8, isCompleted: true },
          { setNumber: 2, weightKg: 52.5, reps: 8, isCompleted: true },
          { setNumber: 3, weightKg: 55, reps: 7, isCompleted: true },
        ],
      },
      {
        exerciseId: 'ex-dumbbell-lateral-raise',
        exerciseName: 'Dumbbell Lateral Raise',
        targetMuscle: 'Shoulders',
        sets: [
          { setNumber: 1, weightKg: 12, reps: 15, isCompleted: true },
          { setNumber: 2, weightKg: 12, reps: 14, isCompleted: true },
          { setNumber: 3, weightKg: 14, reps: 12, isCompleted: true },
          { setNumber: 4, weightKg: 14, reps: 12, isCompleted: true },
        ],
      },
      {
        exerciseId: 'ex-cable-tricep-pushdown',
        exerciseName: 'Cable Tricep Rope Pushdown',
        targetMuscle: 'Triceps',
        sets: [
          { setNumber: 1, weightKg: 25, reps: 15, isCompleted: true },
          { setNumber: 2, weightKg: 27, reps: 12, isCompleted: true },
          { setNumber: 3, weightKg: 30, reps: 12, isCompleted: true },
        ],
      },
    ],
    personalRecordsBroken: [],
  },
  {
    id: 'cw-02',
    routineId: 'routine-leg-quads-glutes',
    routineName: 'Leg Day - Quad & Posterior Chain',
    startTime: '2026-08-29T10:15:00Z',
    endTime: '2026-08-29T11:20:00Z',
    date: '2026-08-29',
    durationSeconds: 3900,
    totalVolumeKg: 13420,
    totalSetsCompleted: 17,
    totalRepsCompleted: 162,
    caloriesBurned: 520,
    exercises: [
      {
        exerciseId: 'ex-barbell-back-squat',
        exerciseName: 'Barbell Back Squat',
        targetMuscle: 'Legs',
        sets: [
          { setNumber: 1, weightKg: 110, reps: 8, isCompleted: true },
          { setNumber: 2, weightKg: 115, reps: 8, isCompleted: true },
          { setNumber: 3, weightKg: 120, reps: 6, isCompleted: true },
          { setNumber: 4, weightKg: 125, reps: 5, isCompleted: true },
        ],
      },
      {
        exerciseId: 'ex-romanian-deadlift',
        exerciseName: 'Romanian Deadlift',
        targetMuscle: 'Legs',
        sets: [
          { setNumber: 1, weightKg: 36, reps: 10, isCompleted: true },
          { setNumber: 2, weightKg: 38, reps: 10, isCompleted: true },
          { setNumber: 3, weightKg: 40, reps: 10, isCompleted: true },
        ],
      },
    ],
    personalRecordsBroken: [],
  },
  {
    id: 'cw-03',
    routineId: 'routine-pull-strength',
    routineName: 'Pull Day - Lat & Upper Back Shred',
    startTime: '2026-08-28T17:30:00Z',
    endTime: '2026-08-28T18:30:00Z',
    date: '2026-08-28',
    durationSeconds: 3600,
    totalVolumeKg: 10850,
    totalSetsCompleted: 17,
    totalRepsCompleted: 155,
    caloriesBurned: 460,
    exercises: [
      {
        exerciseId: 'ex-conventional-deadlift',
        exerciseName: 'Barbell Conventional Deadlift',
        targetMuscle: 'Back',
        sets: [
          { setNumber: 1, weightKg: 130, reps: 6, isCompleted: true },
          { setNumber: 2, weightKg: 140, reps: 5, isCompleted: true },
          { setNumber: 3, weightKg: 145, reps: 5, isCompleted: true },
          { setNumber: 4, weightKg: 150, reps: 4, isCompleted: true },
        ],
      },
      {
        exerciseId: 'ex-lat-pulldown',
        exerciseName: 'Wide-Grip Lat Pulldown',
        targetMuscle: 'Back',
        sets: [
          { setNumber: 1, weightKg: 65, reps: 12, isCompleted: true },
          { setNumber: 2, weightKg: 70, reps: 10, isCompleted: true },
          { setNumber: 3, weightKg: 75, reps: 10, isCompleted: true },
        ],
      },
    ],
    personalRecordsBroken: [
      {
        exerciseId: 'ex-conventional-deadlift',
        exerciseName: 'Barbell Conventional Deadlift',
        weightKg: 150,
        reps: 4,
        previous1RM: 165,
        new1RM: 170,
      },
    ],
  },
  {
    id: 'cw-04',
    routineId: 'routine-upper-hypertrophy',
    routineName: 'Upper Body Savage',
    startTime: '2026-08-26T08:30:00Z',
    endTime: '2026-08-26T09:20:00Z',
    date: '2026-08-26',
    durationSeconds: 3000,
    totalVolumeKg: 8200,
    totalSetsCompleted: 17,
    totalRepsCompleted: 170,
    caloriesBurned: 390,
    exercises: [],
    personalRecordsBroken: [],
  },
  {
    id: 'cw-05',
    routineId: 'routine-push-power',
    routineName: 'Push Day - Hypertrophy & Power',
    startTime: '2026-08-24T09:00:00Z',
    endTime: '2026-08-24T09:50:00Z',
    date: '2026-08-24',
    durationSeconds: 3000,
    totalVolumeKg: 8600,
    totalSetsCompleted: 17,
    totalRepsCompleted: 145,
    caloriesBurned: 405,
    exercises: [],
    personalRecordsBroken: [],
  },
];

export const SEED_FOODS: FoodItem[] = [
  {
    id: 'food-chicken-breast',
    name: 'Grilled Chicken Breast',
    brand: 'Fresh Butcher Cut',
    category: 'Proteins',
    servingSize: '100g cooked',
    servingUnit: 'g',
    baseServingQty: 100,
    calories: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    fiberG: 0,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'food-whey-isolate',
    name: '100% Whey Protein Isolate',
    brand: 'Gold Standard / Optimum',
    category: 'Supplements',
    servingSize: '1 scoop (32g)',
    servingUnit: 'scoop',
    baseServingQty: 1,
    calories: 120,
    proteinG: 25,
    carbsG: 2,
    fatG: 1,
    fiberG: 0,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'food-eggs-whole',
    name: 'Large Whole Eggs (Boiled/Fried)',
    category: 'Proteins',
    servingSize: '2 large eggs (100g)',
    servingUnit: 'eggs',
    baseServingQty: 2,
    calories: 144,
    proteinG: 12.6,
    carbsG: 0.8,
    fatG: 9.8,
    fiberG: 0,
    isVegetarian: true,
  },
  {
    id: 'food-egg-whites',
    name: 'Liquid Egg Whites',
    category: 'Proteins',
    servingSize: '100ml',
    servingUnit: 'ml',
    baseServingQty: 100,
    calories: 52,
    proteinG: 11,
    carbsG: 0.7,
    fatG: 0.2,
    fiberG: 0,
    isVegetarian: true,
  },
  {
    id: 'food-paneer-raw',
    name: 'Fresh Malai Paneer',
    category: 'Dairy',
    servingSize: '100g',
    servingUnit: 'g',
    baseServingQty: 100,
    calories: 265,
    proteinG: 18,
    carbsG: 4,
    fatG: 20,
    fiberG: 0,
    isVegetarian: true,
    isIndianRegional: true,
  },
  {
    id: 'food-low-fat-paneer',
    name: 'Low Fat Paneer',
    category: 'Dairy',
    servingSize: '100g',
    servingUnit: 'g',
    baseServingQty: 100,
    calories: 145,
    proteinG: 25,
    carbsG: 3,
    fatG: 3.5,
    fiberG: 0,
    isVegetarian: true,
    isIndianRegional: true,
  },
  {
    id: 'food-greek-yogurt',
    name: 'Non-Fat Greek Yogurt',
    brand: 'Chobani / Fage',
    category: 'Dairy',
    servingSize: '170g (3/4 cup)',
    servingUnit: 'g',
    baseServingQty: 170,
    calories: 100,
    proteinG: 18,
    carbsG: 6,
    fatG: 0,
    fiberG: 0,
    isVegetarian: true,
  },
  {
    id: 'food-rolled-oats',
    name: 'Rolled Oats (Dry)',
    brand: 'Quaker',
    category: 'Carbs',
    servingSize: '50g (1/2 cup)',
    servingUnit: 'g',
    baseServingQty: 50,
    calories: 190,
    proteinG: 6.5,
    carbsG: 34,
    fatG: 3,
    fiberG: 5,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-white-rice',
    name: 'Cooked Basmati / Jasmine White Rice',
    category: 'Carbs',
    servingSize: '150g (1 cup)',
    servingUnit: 'g',
    baseServingQty: 150,
    calories: 195,
    proteinG: 4.2,
    carbsG: 43,
    fatG: 0.5,
    fiberG: 0.8,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-sweet-potato',
    name: 'Baked Sweet Potato',
    category: 'Carbs',
    servingSize: '150g',
    servingUnit: 'g',
    baseServingQty: 150,
    calories: 135,
    proteinG: 3,
    carbsG: 31,
    fatG: 0.2,
    fiberG: 4.5,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-whole-wheat-roti',
    name: 'Whole Wheat Chapati / Roti (No Ghee)',
    category: 'Carbs',
    servingSize: '1 medium roti (35g)',
    servingUnit: 'roti',
    baseServingQty: 1,
    calories: 85,
    proteinG: 3.2,
    carbsG: 16.5,
    fatG: 0.5,
    fiberG: 2.8,
    isVegetarian: true,
    isVegan: true,
    isIndianRegional: true,
  },
  {
    id: 'food-yellow-dal',
    name: 'Cooked Yellow Moong / Toor Dal',
    category: 'Carbs',
    servingSize: '1 bowl (150g)',
    servingUnit: 'bowl',
    baseServingQty: 1,
    calories: 160,
    proteinG: 9,
    carbsG: 24,
    fatG: 3,
    fiberG: 6,
    isVegetarian: true,
    isVegan: true,
    isIndianRegional: true,
  },
  {
    id: 'food-peanut-butter',
    name: 'Natural All-Natural Peanut Butter',
    category: 'Fats',
    servingSize: '2 tbsp (32g)',
    servingUnit: 'tbsp',
    baseServingQty: 2,
    calories: 190,
    proteinG: 8,
    carbsG: 7,
    fatG: 16,
    fiberG: 2.5,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-raw-almonds',
    name: 'Raw California Almonds',
    category: 'Fats',
    servingSize: '28g (23 almonds)',
    servingUnit: 'g',
    baseServingQty: 28,
    calories: 164,
    proteinG: 6,
    carbsG: 6,
    fatG: 14,
    fiberG: 3.5,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-banana',
    name: 'Fresh Medium Banana',
    category: 'Fruits',
    servingSize: '1 medium (118g)',
    servingUnit: 'medium',
    baseServingQty: 1,
    calories: 105,
    proteinG: 1.3,
    carbsG: 27,
    fatG: 0.3,
    fiberG: 3.1,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-blueberries',
    name: 'Fresh Blueberries',
    category: 'Fruits',
    servingSize: '100g (1 cup)',
    servingUnit: 'g',
    baseServingQty: 100,
    calories: 57,
    proteinG: 0.7,
    carbsG: 14.5,
    fatG: 0.3,
    fiberG: 2.4,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-atlantic-salmon',
    name: 'Pan-Seared Atlantic Salmon',
    category: 'Proteins',
    servingSize: '125g fillet',
    servingUnit: 'g',
    baseServingQty: 125,
    calories: 260,
    proteinG: 28,
    carbsG: 0,
    fatG: 16,
    fiberG: 0,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'food-fresh-avocado',
    name: 'Fresh Hass Avocado',
    category: 'Fats',
    servingSize: '1/2 medium (75g)',
    servingUnit: 'half',
    baseServingQty: 1,
    calories: 120,
    proteinG: 1.5,
    carbsG: 6,
    fatG: 11,
    fiberG: 5,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'food-steamed-broccoli',
    name: 'Steamed Florets Broccoli',
    category: 'Vegetables',
    servingSize: '100g',
    servingUnit: 'g',
    baseServingQty: 100,
    calories: 35,
    proteinG: 2.8,
    carbsG: 7,
    fatG: 0.4,
    fiberG: 2.6,
    isVegetarian: true,
    isVegan: true,
  },
];

// Today's date helper
const todayStr = new Date().toISOString().split('T')[0];

export const SEED_LOGGED_MEALS: LoggedFoodItem[] = [
  {
    id: 'log-01',
    foodId: 'food-rolled-oats',
    name: 'Rolled Oats (Dry)',
    meal: 'breakfast',
    date: todayStr,
    servings: 1,
    servingUnit: '50g',
    calories: 190,
    proteinG: 6.5,
    carbsG: 34,
    fatG: 3,
    fiberG: 5,
    timestamp: '2026-09-01T08:15:00Z',
  },
  {
    id: 'log-02',
    foodId: 'food-whey-isolate',
    name: '100% Whey Protein Isolate',
    meal: 'breakfast',
    date: todayStr,
    servings: 1.2,
    servingUnit: 'scoop',
    calories: 144,
    proteinG: 30,
    carbsG: 2.4,
    fatG: 1.2,
    fiberG: 0,
    timestamp: '2026-09-01T08:15:00Z',
  },
  {
    id: 'log-03',
    foodId: 'food-peanut-butter',
    name: 'Natural All-Natural Peanut Butter',
    meal: 'breakfast',
    date: todayStr,
    servings: 0.8,
    servingUnit: 'tbsp',
    calories: 152,
    proteinG: 6.4,
    carbsG: 5.6,
    fatG: 12.8,
    fiberG: 2,
    timestamp: '2026-09-01T08:15:00Z',
  },
  {
    id: 'log-04',
    foodId: 'food-chicken-breast',
    name: 'Grilled Chicken Breast',
    meal: 'lunch',
    date: todayStr,
    servings: 1.8,
    servingUnit: '100g',
    calories: 297,
    proteinG: 55.8,
    carbsG: 0,
    fatG: 6.5,
    fiberG: 0,
    timestamp: '2026-09-01T13:00:00Z',
  },
  {
    id: 'log-05',
    foodId: 'food-white-rice',
    name: 'Basmati White Rice',
    meal: 'lunch',
    date: todayStr,
    servings: 1.5,
    servingUnit: '150g',
    calories: 292,
    proteinG: 6.3,
    carbsG: 64.5,
    fatG: 0.7,
    fiberG: 1.2,
    timestamp: '2026-09-01T13:00:00Z',
  },
  {
    id: 'log-06',
    foodId: 'food-steamed-broccoli',
    name: 'Steamed Broccoli',
    meal: 'lunch',
    date: todayStr,
    servings: 1.5,
    servingUnit: '100g',
    calories: 52,
    proteinG: 4.2,
    carbsG: 10.5,
    fatG: 0.6,
    fiberG: 3.9,
    timestamp: '2026-09-01T13:00:00Z',
  },
  {
    id: 'log-07',
    foodId: 'food-greek-yogurt',
    name: 'Non-Fat Greek Yogurt',
    meal: 'snacks',
    date: todayStr,
    servings: 1,
    servingUnit: '170g',
    calories: 100,
    proteinG: 18,
    carbsG: 6,
    fatG: 0,
    fiberG: 0,
    timestamp: '2026-09-01T16:30:00Z',
  },
  {
    id: 'log-08',
    foodId: 'food-blueberries',
    name: 'Fresh Blueberries',
    meal: 'snacks',
    date: todayStr,
    servings: 0.8,
    servingUnit: '100g',
    calories: 45,
    proteinG: 0.6,
    carbsG: 11.6,
    fatG: 0.2,
    fiberG: 1.9,
    timestamp: '2026-09-01T16:30:00Z',
  },
];

export const SEED_WATER_LOGS: WaterLog[] = [
  { id: 'w-01', date: todayStr, amountMl: 500, timestamp: '2026-09-01T07:30:00Z' },
  { id: 'w-02', date: todayStr, amountMl: 750, timestamp: '2026-09-01T11:00:00Z' },
  { id: 'w-03', date: todayStr, amountMl: 500, timestamp: '2026-09-01T14:30:00Z' },
  { id: 'w-04', date: todayStr, amountMl: 250, timestamp: '2026-09-01T16:00:00Z' },
];

export const SEED_WEIGHT_ENTRIES: WeightEntry[] = [
  { id: 'wt-01', date: '2026-08-10', weightKg: 82.0, note: 'Starting baseline', timestamp: '2026-08-10T07:00:00Z' },
  { id: 'wt-02', date: '2026-08-13', weightKg: 81.5, note: 'Post deload', timestamp: '2026-08-13T07:00:00Z' },
  { id: 'wt-03', date: '2026-08-16', weightKg: 81.0, timestamp: '2026-08-16T07:00:00Z' },
  { id: 'wt-04', date: '2026-08-19', weightKg: 80.4, note: 'Water weight stabilized', timestamp: '2026-08-19T07:00:00Z' },
  { id: 'wt-05', date: '2026-08-22', weightKg: 79.9, timestamp: '2026-08-22T07:00:00Z' },
  { id: 'wt-06', date: '2026-08-25', weightKg: 79.2, note: 'Great deficit consistency', timestamp: '2026-08-25T07:00:00Z' },
  { id: 'wt-07', date: '2026-08-28', weightKg: 78.8, timestamp: '2026-08-28T07:00:00Z' },
  { id: 'wt-08', date: '2026-08-31', weightKg: 78.4, note: 'Fast morning weigh-in', timestamp: '2026-08-31T07:00:00Z' },
  { id: 'wt-09', date: todayStr, weightKg: 78.2, note: 'New lowest weigh-in!', timestamp: '2026-09-01T07:00:00Z' },
];
